# Load required R packages for the application
require("rstudioapi")  
require("dplyr")      
require("stringr")     
require("tidyverse")   
require("BiocManager") 
require("ggplot2")     
require("qtl2")        
require("grid")        
require("ggrepel")     
require("gridGraphics")
require("ggpubr")     
require("shiny")      
require("shinyFiles") 
require("bslib")      
require("spsComps")   
require("DT")         
require("shinyjs")    
require("shinycssloaders")
require("data.table") 
require("reshape2")   
require("plotly")     
require("ggiraph")    
require("writexl")   
require("fontawesome")
require("debounce")

# Set maximum file upload size for Shiny (20GB)
options(shiny.maxRequestSize = 20000*1024^2)

source("modules/data_import.R")
source("modules/helper_functions.R")