#' Plotly Scan App Module
#' 
#' This app has a point-click feature not yet implemented.
#' See `kalynn_R/latest_app_kalynn/app.R`.
#' Also not sure if `selected_chr` should be here or elsewhere.
#'
#' @param id shiny identifier
#' @param main_par reactive list with selected_dataset, LOD_thr and which_trait
#' @param scan_table reactive dataframe from scanServer
#' @param peak_table reactive dataframe from peakServer
#'
#' @importFrom DT datatable DTOutput renderDT
#' @importFrom shiny actionButton h4 moduleServer nearPoints NS plotOutput
#'             reactive reactiveVal renderPlot renderUI req setProgress shinyApp
#'             uiOutput withProgress
#' @importFrom bslib card card_header page_sidebar sidebar
#' @importFrom shinycssloaders withSpinner
#' @importFrom dplyr across mutate where
#' @importFrom stringr str_split
#' @importFrom htmltools tags
#' @importFrom plotly event_data plotlyOutput renderPlotly
#'
#' @export
scanlyApp <- function() {
  ui <- bslib::page_sidebar(
    title = "Test Plotly Scan",
    sidebar = bslib::sidebar("side_panel",
      mainParInput("main_par"), # "selected_dataset", "LOD_thr"
      mainParUI("main_par"),    # "which_trait"
      scanlyInput("scanly")),   # "selected_chr"
    bslib::card(
      bslib::card_header("LOD profile"),
      scanlyOutput("scanly")),
    bslib::card(
      bslib::card_header("Clicked Peak"),
      scanlyUI("scanly"))
  )
  server <- function(input, output, session) {
      import <- importServer("import")
      main_par <- mainParServer("main_par", import)
      scan_table <- scanServer("scan_table", main_par, import)
      peak_table <- peakServer("peak_table", main_par, import)
      scanlyServer("scanly", main_par, scan_table, peak_table)
  }
  shiny::shinyApp(ui = ui, server = server)
}
#' @rdname scanApp
#' @export
scanlyServer <- function(id, main_par, scan_table, peak_table) {
  shiny::moduleServer(id, function(input, output, session) {
    ns <- session$ns
    # Plotly plot
    output$scan_plot <- shiny::renderUI({
      plotly::plotlyOutput(ns("render_plot")) |>
        shinycssloaders::withSpinner(type = 8, color = "#3498db")
    })
    scanly_plot <- shiny::reactive({
      req(scan_table(), peak_table(), input$selected_chr)
      ggplotly_qtl_scan(scan_table(), peak_table(), input$selected_chr, "scanly_plot")
    })
    output$render_plot <- plotly::renderPlotly({
      req(scanly_plot())
    })
    # Handle clicked points display ** not quite right yet **
    # Want observeEvent for peak_table() to reset the clicked_point_info dataframe.
    # want observeEvent for plotly_click to also reset the clicked_point_info dataframe.
    # This should probably be a reactive, but it could be sparked by one or the other.
    # This is a bit tricky because we want to use the plotly click event data
    # if present, but when peak_table() changes, we want to reset the peak info.
    # We can use a reactive to store the clicked point information
    # and update it when the plotly click event occurs.
    # We can also use a reactive to store the peak info
    # and update it when the peak_table() changes.
    # We can use the plotly click event data to get the x and y coordinates
    # of the clicked point and use that to filter the peak_table() data.
    # We can then use that to update the clicked_point_info dataframe.
    # We can also use the plotly click event data to get the x and y coordinates
    # of the clicked point and use that to filter the peak_table() data.
    # We can then use that to update the clicked_point_info dataframe.
    # Some of this was generated by ChatGPT and needs to be cleaned up.
    which_peak <- shiny::reactive({
      shiny::req(peak_table(), main_par$LOD_thr)
      ordered_peaks <- highest_peaks(peak_table(), main_par$LOD_thr)
      ordered_peaks$marker[1]
    })
    plotly_click <- shiny::reactive({
      plotly::event_data("plotly_click", source = "scanly_plot")
    })
    # `stable_peak()` stores the stable peak information for table display.
    # `max_peak()` has maximum peak when reactives change.
    # `stable_peak()` changes when `max_peak()` or `plotly_click()` changes.
    # `stable_peak()` is not reactive but is updated by reactives.
    stable_peak <- shiny::reactiveVal(NULL)
    max_peak <- shiny::reactive({
      shiny::req(peak_info(peak_table(), scan_table(), which_peak()))
      out <- peak_info(peak_table(), scan_table(), which_peak())
      stable_peak(out)
      out
    })
    observeEvent(shiny::req(plotly_click()), {
      shiny::req(peak_info(peak_table(), scan_table(), which_peak()))
      out <- peak_info(peak_table(), scan_table(), which_peak(), plotly_click())
      stable_peak(out)
      out
    })
    output$clicked_point_info <- DT::renderDT({
      shiny::req(max_peak())
      DT::datatable(
        stable_peak(),
        options = list(dom = 't', ordering = FALSE, pageLength = 1),
        rownames = FALSE,
        class = 'compact hover',
        caption = htmltools::tags$caption(
          style = 'caption-side: top; text-align: left; color: #2c3e50; font-weight: bold; font-size: 14px;',
          'Peak Information and Strain Effects'))
    })
    output$high_peak <- shiny::renderUI({
      list(
        shiny::renderPrint({
          if(shiny::isTruthy(plotly_click())) {
            paste("Clicked point: x =", plotly_click()$x, ", y =", plotly_click()$y)
          } else {
            "No point clicked yet."
          }
        }),
        DT::DTOutput(ns("clicked_point_info")))
    })
    # Add observer for plotly double click event
    shiny::observeEvent(
      plotly::event_data("plotly_doubleclick", source = "scanly_plot"), {
      if(input$selected_chr != "All") {
        shiny::updateSelectInput(session, "selected_chr", selected = "All")
      }
    })
  })
}
#' @rdname scanApp
#' @export
scanlyInput <- function(id) {
  ns <- shiny::NS(id)
  shiny::selectInput(ns("selected_chr"), "Zoom to Chromosome:",
    choices = c("All",
                "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
                "11", "12", "13", "14", "15", "16", "17", "18", "19",
                "X", "Y", "M"),
    selected = "All",
    width = "150px")
}
#' @rdname scanApp
#' @export
scanlyUI <- function(id) {
  ns <- shiny::NS(id)
  shiny::uiOutput(ns("high_peak"))
}
#' @rdname scanApp
#' @export
scanlyOutput <- function(id) {
  ns <- shiny::NS(id)
  shiny::uiOutput(ns("scan_plot"))
}
